#!/bin/bash

if [[ $# -lt 1 ]]; then
    echo "Usage: [runNumber] "
else

    runNr=$(printf "%04d" $1)
    echo Making directory run_$runNr
    mkdir run_$runNr
    cd run_$runNr
    echo Linking Conf directory
    ln -s ../Conf
    echo Linking Data directory
    ln -s /Volumes/My\ Passport/EXP_016/AgataData/run_$runNr*/Data
    if [[ -f ../gen_conf/gen_conf_$runNr.py ]]; then
        ln -s ../GenConf/gen_conf_$runNr.py gen_conf.py
    else
        cp ../GenConf/gen_conf.py ../GenConf/gen_conf_$runNr.py
        ln -s ../GenConf/gen_conf_$runNr.py gen_conf.py
    fi
    echo Linking gen_conf
    ./gen_conf.py
    # ls /Volumes/My Passport/EXP_016/AgataData/run_$runNr*/Data/prisma/*rucaenmps >> inputfiles.txt
    #ll "/Volumes/My Passport/EXP_016/AncillaryData/run_$runNr/Data/ancillaries/" | wc -l
    totFiles=$( ls -lthr  /Volumes/My\ Passport/EXP_016/AncillaryData/run_$runNr*/Data/ancillaries/ | wc -l)
    totFiles=$(( totFiles-1 ))
    for ((i = 0 ; i < totFiles ; i++ )); do
        filNum=$(printf "%04d" $i)
        ln -s /Volumes/My\ Passport/EXP_016/AncillaryData/run_$runNr*/Data/ancillaries/*$filNum\.adf prisma_$filNum\.adf
    done

    #ln -s
    # ln -s ../gen_conf/filter.conf
    ln -s ../Topology/Topology_FromPSAToTreePRISMA.conf
    #PrismaFilters -ifl inputfiles.txt -of prisma_$runNr.adf -ogf -cfg filter.conf
    cd ..

fi

